Repository gapless-tech/create-react-dashboard, pull requests merged in 2019-02, with the labels that each got.

#4 User Settings Config Mockup
  src/components/charts/Pie.js
  src/components/skeleton/content/Content.js
  src/pages/Home.js
  src/pages/UserConfigs/BasicConfigs.js
  src/pages/UserConfigs/Notifications.js
  src/pages/UserConfigs/Security.js
  src/pages/UserProfile.js
  src/pages/UserSettings.css
  src/pages/UserSettings.js
  src/pages/index.js
  src/routes/private.js
  src/routes/public.js
Labels: enhancement, help wanted

#13 added configs for prettier, husky and linter
  .editorconfig
  .eslintrc.json
  .prettierrc
  package.json
  yarn.lock
Labels: help wanted

#12 Graphs update
  package.json
  src/components/graphs/Bar.js
  src/components/graphs/Line.js
  src/components/graphs/Pie.js
  src/pages/UserConfigs/BasicConfigs.js
  src/pages/UserConfigs/Security.js
  src/pages/graphs/Bars.js
  src/pages/graphs/Lines.js
  src/pages/graphs/Pies.js
  src/pages/index.js
  src/routes/private.js
  yarn.lock
Labels: enhancement

#15 feat: Add breadcrumb
  src/components/skeleton/content/Content.js
  src/components/skeleton/layout/Layout.js
  src/components/skeleton/sider/Sider.js
Labels: enhancement
